version: '3.8'

services:
  demo-docker-compose:
    build: .
    container_name: app-cine
    networks:
      - net-cinema
    ports: 
      - 80:80
    depends_on:
      - cinema_bd

  cinema_bd:
    image: mongo
    container_name: cinema-db
    networks: 
      - net-cinema
    ports:
      - 27017:27017
networks:
  net-cinema:

    